// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'

type SlackChannel = {
  name: string
  id: string
}

type Response = {
  data: SlackChannel[]
  hasNextPage: boolean
}

const channels: SlackChannel[] = [
  { name: 'general', id: 'C03CNQ18X98' },
  { name: 'bugs', id: 'C03NXMSL3S5' },
  { name: 'tweets', id: 'C03P8Q9R1AL' },
  { name: 'deals', id: 'C04E2VDU57E' },
  { name: 'feedback', id: 'C04E6T90Y8Z' },
  { name: 'engineering', id: 'C04ECKBPHTK' },
  { name: 'wip', id: 'C04ES2B8N3B' },
  { name: 'slack-app-testing', id: 'C04FYSC2UAU' },
  { name: 'design', id: 'C04HERXK3QU' },
  { name: 'product', id: 'C04HNUN79L7' },
  { name: 'api-alerts', id: 'C04J3BUV5S7' },
  { name: 'web-alerts', id: 'C04J5UXQNAG' },
  { name: 'rant', id: 'C04JBEBFUDC' },
  { name: 'noob', id: 'C04JC2274H3' },
  { name: 'eng-ops', id: 'C04JG4BN3B3' },
  { name: 'wins', id: 'C04JK0H9JL8' },
  { name: 'shitpost', id: 'C04K37Z10QH' },
  { name: 'shipped', id: 'C04KJL01BK2' },
  { name: 'signups', id: 'C04LYDVE8E5' },
  { name: 'office', id: 'C04M2B0AFPW' },
  { name: 'inspo', id: 'C04P8582DD4' },
  { name: 'yolo', id: 'C04S5FPEX54' },
  { name: 'proj-canvas-comments', id: 'C050GN7GE9G' },
  { name: 'proj-custom-digests', id: 'C050KFD5BNG' },
  { name: 'community', id: 'C0514RWGTUJ' },
  { name: 'emails', id: 'C052YUTP5QA' },
  { name: 'nyc-2023', id: 'C054FG72RN1' },
  { name: 'proj-public-posts', id: 'C0557FHR933' },
  { name: 'proj-task-integrations', id: 'C055XCAFTEG' },
  { name: 'proj-billing', id: 'C056QDJTX7X' },
  { name: 'proj-pricing-page', id: 'C0537PH6971' },
  { name: 'proj-favorites', id: 'C05FGHFGA0H' },
  { name: 'proj-private-projects', id: 'C054US44P7V' },
  { name: 'design-magic', id: 'C07ZHYE1JU9' },
  { name: 'engineer-hub', id: 'C08ATGMFBG9' },
  { name: 'product-pandemonium', id: 'C08H6X3GLFF' },
  { name: 'creative-gurus', id: 'C08LXCRKVBG' },
  { name: 'code-commandos', id: 'C08R3R1NFGM' },
  { name: 'sketch-a-holics', id: 'C08TG6Y4HRV' },
  { name: 'bug-busters', id: 'C08UP7NQQR6' },
  { name: 'design-dynamos', id: 'C0907DTR1SK' },
  { name: 'product-explorers', id: 'C092R7LME1N' },
  { name: 'tech-wizards', id: 'C09829US6F5' },
  { name: 'pixel-party', id: 'C09BTEG5V61' },
  { name: 'code-masters', id: 'C09F5RTNMMK' },
  { name: 'sketch-central', id: 'C09KX49E5D9' },
  { name: 'innovation-league', id: 'C09PAQ13D97' },
  { name: 'product-pioneers', id: 'C09V3DZ5QNN' },
  { name: 'design-fiesta', id: 'C09YUQSGVMV' },
  { name: 'engineering-elite', id: 'C0A42YCS4S5' },
  { name: 'fun-with-code', id: 'C0A7WSS84H9' },
  { name: 'creative-ninjas', id: 'C0AD0PSR6E3' },
  { name: 'bug-squashers', id: 'C0AHSU2Z9C7' },
  { name: 'product-playground', id: 'C0AKP89S4JN' },
  { name: 'sketch-squad', id: 'C0AN3Z6MR5V' },
  { name: 'tech-talks', id: 'C0AS6TJN02V' },
  { name: 'pixel-pirates', id: 'C0AX54JJVGB' },
  { name: 'code-jam', id: 'C0B3CVPRR0K' },
  { name: 'design-genius', id: 'C0B86G22L53' },
  { name: 'product-gang', id: 'C0BDQZ7JZ53' },
  { name: 'tech-hackers', id: 'C0BJG9WJN1E' },
  { name: 'sketch-sprint', id: 'C0BP42QF40R' },
  { name: 'innovation-space', id: 'C0BS3EJP7HA' },
  { name: 'code-blitz', id: 'C0C2S34ZMCY' },
  { name: 'creative-circus', id: 'C0C8SQW1Z0Z' },
  { name: 'bug-blitz', id: 'C0CGN95N27Q' },
  { name: 'product-geeks', id: 'C0CNDU6EXR3' },
  { name: 'design-dive', id: 'C0CVH7RAKGJ' },
  { name: 'tech-titans', id: 'C0CYDEWM6MR' },
  { name: 'pixel-planet', id: 'C0D2GFXF7A0' },
  { name: 'code-crushers', id: 'C0D8C42CGGG' },
  { name: 'sketch-smashers', id: 'C0DEZ3C6QRX' },
  { name: 'innovation-arena', id: 'C0DK1B67ZGC' },
  { name: 'product-peeps', id: 'C0DQPTNRQNU' },
  { name: 'tech-tales', id: 'C0DV6GVMV41' },
  { name: 'design-den', id: 'C0E21JUEBH7' },
  { name: 'bug-blasters', id: 'C0E8W47SNSB' },
  { name: 'product-palooza', id: 'C0EF6B9SA2F' },
  { name: 'creative-crusade', id: 'C0ELCMQMTK1' },
  { name: 'code-connect', id: 'C0ERDKA1U39' },
  { name: 'sketch-stars', id: 'C0EYR5UFBMU' },
  { name: 'innovation-lounge', id: 'C0F4TNSZK85' },
  { name: 'tech-tribe', id: 'C0FB1SJ2K05' },
  { name: 'pixel-palace', id: 'C0FH8TN0T8M' },
  { name: 'code-capers', id: 'C0FM7V2T0Y1' },
  { name: 'design-dazzle', id: 'C0FT6PEMCQC' },
  { name: 'bug-hunt', id: 'C0G2FE5R1JT' },
  { name: 'product-party', id: 'C0G8XJXK0YF' },
  { name: 'tech-time', id: 'C0GG0G12T8G' },
  { name: 'sketch-symphony', id: 'C0GLFMC2VH2' },
  { name: 'innovation-hub', id: 'C0GRZ4YGS5W' },
  { name: 'code-castle', id: 'C0H2CJ9MHFE' },
  { name: 'creative-cafe', id: 'C0H99Z2UYS9' },
  { name: 'bug-safari', id: 'C0HF3CBH9R1' },
  { name: 'product-parade', id: 'C0HL7U7BPSK' },
  { name: 'design-doodle', id: 'C0HQ6H8J9KT' },
  { name: 'tech-tempest', id: 'C0HXQT6FEY5' },
  { name: 'pixel-party', id: 'C0J3FBY06RE' },
  { name: 'code-carnival', id: 'C0J9MJ1MSA3' },
  { name: 'sketch-sessions', id: 'C0JF3SE7EPW' },
  { name: 'innovation-inc', id: 'C0JL4KBG83U' },
  { name: 'product-playpen', id: 'C0JS7CAQW09' },
  { name: 'tech-tornado', id: 'C0K1G0EF0CR' },
  { name: 'design-delights', id: 'C0K7PCZZ5S7' },
  { name: 'bug-bounty', id: 'C0KG43QDQ1H' },
  { name: 'product-pal', id: 'C0KP81QKP9M' },
  { name: 'creative-confab', id: 'C0KT62YJ9VQ' },
  { name: 'code-concoctions', id: 'C0L1BY9H6DG' },
  { name: 'innovation-garden', id: 'C0L71E1Q1T8' },
  { name: 'design-discourse', id: 'C0LEYP6UZQ8' },
  { name: 'bug-blast', id: 'C0LK5TEA0J1' },
  { name: 'product-peak', id: 'C0LRA6NPN3L' },
  { name: 'tech-terrain', id: 'C0M3DDYB5A1' },
  { name: 'sketch-showcase', id: 'C0M9NS7E48M' },
  { name: 'innovation-lair', id: 'C0MEK4PYGZ4' },
  { name: 'code-chaos', id: 'C0MLP3J06RA' },
  { name: 'design-daydream', id: 'C0MPUZYNQBH' },
  { name: 'bug-blasters', id: 'C0N2K1RHY3R' },
  { name: 'product-pathfinders', id: 'C0N8Y0R24DB' },
  { name: 'tech-tinkerers', id: 'C0NFUMC0EBZ' },
  { name: 'sketch-snipers', id: 'C0NL4JNH0MF' },
  { name: 'innovation-club', id: 'C0NUUZTC7QD' },
  { name: 'code-circus', id: 'C0P0V5ZGJK6' },
  { name: 'design-divas', id: 'C0P7TBX4XCA' },
  { name: 'bug-hunters', id: 'C0PFZM2UM2N' },
  { name: 'product-pirates', id: 'C0PL2KZ6Q0K' },
  { name: 'tech-tales', id: 'C0PPZ24KJTV' },
  { name: 'sketch-sanctuary', id: 'C0Q1HZZ0BE1' },
  { name: 'innovation-station', id: 'C0Q8QCVF1JJ' },
  { name: 'code-crunchers', id: 'C0QFM41LPKB' },
  { name: 'design-doodle', id: 'C0QMVGZH2B5' },
  { name: 'bug-squash', id: 'C0R3E2MZ01N' },
  { name: 'product-planet', id: 'C0R9EZXMUS6' },
  { name: 'tech-talk', id: 'C0RF3B9VSMK' },
  { name: 'pixel-perfection', id: 'C0RMAFNNHQ2' },
  { name: 'code-commandos', id: 'C0S2P7Z0XN1' },
  { name: 'design-dazzle', id: 'C0S8V3W8U6T' },
  { name: 'bug-blitz', id: 'C0SEDETR7D5' },
  { name: 'product-party', id: 'C0SMCFD6YH5' },
  { name: 'tech-time', id: 'C0SXQEVNVPR' }
]

export default function handler(req: NextApiRequest, res: NextApiResponse<Response>) {
  console.log(req.url)
  const { searchParams } = new URL(`http://localhost/${req.url}`)
  const searchParam = searchParams.get('q')
  const filteredChannels = searchParam ? channels.filter((channel) => channel.name.includes(searchParam)) : channels
  const pageParam = searchParams.get('page')
  const page = pageParam ? parseInt(pageParam) : 1
  const perPage = 10
  const start = (page - 1) * perPage
  const end = start + perPage
  const hasNextPage = end < filteredChannels.length

  res.status(200).json({ data: filteredChannels.slice(start, end), hasNextPage })
}
